// <auto-generated />
using System;
using CadastroDePacientesBe3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadastroDePacientesBe3.Migrations
{
    [DbContext(typeof(DB5566Context))]
    [Migration("20200218212122_NewFields")]
    partial class NewFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CadastroDePacientesBe3.Models.Clientes", b =>
                {
                    b.Property<int>("Prontuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .HasMaxLength(20);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnName("CPF")
                        .HasMaxLength(14);

                    b.Property<DateTime>("DtNasc")
                        .HasColumnName("Dt_Nasc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DtValidade")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FoneRes")
                        .IsRequired()
                        .HasColumnName("Fone_Res")
                        .HasMaxLength(20);

                    b.Property<short?>("IdConvenio")
                        .IsRequired()
                        .HasColumnName("ID_Convenio");

                    b.Property<short?>("IdUF")
                        .IsRequired();

                    b.Property<string>("NCarteirinha")
                        .IsRequired()
                        .HasColumnName("N_Carteirinha")
                        .HasMaxLength(20);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasColumnName("Nome_Mae")
                        .HasMaxLength(50);

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnName("RG")
                        .HasMaxLength(15);

                    b.Property<byte>("Sexo");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Prontuario");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CadastroDePacientesBe3.Models.Convenios", b =>
                {
                    b.Property<int>("IdConvenio")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_Convenio")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Empresa")
                        .HasMaxLength(50);

                    b.HasKey("IdConvenio");

                    b.ToTable("Convenios");
                });
#pragma warning restore 612, 618
        }
    }
}
